name: new_systems_intercession
description: "Таблица смен ПТБ"
publish_to: 'none'

version: 1.1.2+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  data_table_2: ^2.7.2
  shared_preferences: ^2.5.5
  provider: ^6.1.5+1
  http: ^1.6.0
  firebase_core: ^4.10.0
  cloud_firestore: ^6.5.0
  firebase_auth: ^6.5.3
  image_picker: ^1.2.2
  path_provider: ^2.1.6
  firebase_storage: ^13.4.3
  cloudinary: ^1.2.0
  package_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#1976d2"
  adaptive_icon_foreground: "assets/icon/app_icon.png"