// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB72cSIvpRUYRVBIwerPZBG6-YLQP8GLXs',
    appId: '1:393063456146:web:359c59a3cb1bac9127754b',
    messagingSenderId: '393063456146',
    projectId: 'rjd-ptb-employees',
    authDomain: 'rjd-ptb-employees.firebaseapp.com',
    storageBucket: 'rjd-ptb-employees.firebasestorage.app',
    measurementId: 'G-S8BEWDFRGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGP97xjL96uWKJoE9nk0ZQZFm_k4on9Gc',
    appId: '1:393063456146:android:4aaf15036b2d5bd727754b',
    messagingSenderId: '393063456146',
    projectId: 'rjd-ptb-employees',
    storageBucket: 'rjd-ptb-employees.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB72cSIvpRUYRVBIwerPZBG6-YLQP8GLXs',
    appId: '1:393063456146:web:ef9d1b3f62ad14c527754b',
    messagingSenderId: '393063456146',
    projectId: 'rjd-ptb-employees',
    authDomain: 'rjd-ptb-employees.firebaseapp.com',
    storageBucket: 'rjd-ptb-employees.firebasestorage.app',
    measurementId: 'G-P0E821DL4Y',
  );
}
